framework:
  notifier:
    chatter_transports:
    texter_transports:
      infobip: "infobip://059747ab4c869d6a7bd61303c766b66f-7b65660a-3d81-4099-91d9-aba8339dc77e@default?from=ServiceSMS"
    channel_policy:
      # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
      urgent: ["email"]
      high: ["email"]
      medium: ["email"]
      low: ["email"]
    admin_recipients:
      - { email: admin@example.com }
